<a href="https://colab.research.google.com/github/Apoorva-Kulkarni96/Numerical-Python/blob/main/Task2_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
np.__version__,np.show_config

('1.21.5', <function numpy.__config__.show>)

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
v=np.array([[5,2,7,8,4],[1,2,3,4,5]])
a=v.size
b=v.itemsize
c=v.shape
print(a,'\n',b,'\n',c)

10 
 8 
 (2, 5)


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [6]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [7]:
z=np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [8]:
q=np.array([10,20,30,40,50,60,70,80,90,100])
q[::-1]

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [9]:
e=np.array([0,1,2,3,4,5,6,7,8,])
f=e.reshape(3,3)
print(f)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [10]:
p=np.array([1,2,0,0,4,0])
np.nonzero(p)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [11]:
c=np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [12]:
n=np.random.random((3,3,3))
n

array([[[0.62094013, 0.81948571, 0.46035801],
        [0.1872233 , 0.85302398, 0.32905335],
        [0.65830119, 0.5899788 , 0.95462793]],

       [[0.77653944, 0.48172621, 0.70801697],
        [0.56493373, 0.02830088, 0.77275723],
        [0.38657598, 0.71469739, 0.87311521]],

       [[0.78742098, 0.58593684, 0.08278075],
        [0.84333873, 0.90152795, 0.90000556],
        [0.36828036, 0.7993286 , 0.81173199]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [13]:
n=np.random.randint(100,size=(10,10))
print(n)
print(n.min())
print(n.max())

[[14 28 57 55 16 93  5 25 16 84]
 [18 35 90 34 80 49 78 26 68 81]
 [71 66 64 93 89 18 36 15 58 81]
 [27 97 39 87 37 32 60 30 94 93]
 [87  7 34 71 36 36 92 41 86 72]
 [57 81 26 45 28  9 17 35 49 54]
 [54 33 86 66 11 91 94 48 35 71]
 [32 98 34 10  5 33  5 28 62 55]
 [27 11 24 43 17 62 25  7 97 31]
 [12 90 56 26 66 75  0 98 80 40]]
0
98


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [14]:
v=np.random.random(30)
print(v)
print(v.mean())

[0.15080653 0.85055211 0.75046148 0.63569903 0.51186344 0.3990604
 0.81455071 0.67098355 0.10883373 0.33810896 0.31619578 0.8890144
 0.81634516 0.99138982 0.83633703 0.39403754 0.6860191  0.39900892
 0.54339533 0.84736911 0.2247829  0.0401341  0.12722576 0.21690343
 0.14411215 0.59425183 0.10288147 0.05934103 0.92030314 0.02051981]
0.48001625700310735


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [15]:
m=np.ones((5,5))
m[1:-1, 1:-1]=0
#m[1:4,1:4]=0
print(m)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [16]:
l=np.random.randint(100,size=(5,5))
l= np.pad(l, pad_width=1, mode='constant', constant_values=0)
print(l)

[[ 0  0  0  0  0  0  0]
 [ 0 82 30 63 21 49  0]
 [ 0 87 11 54 12  4  0]
 [ 0 68 89 96 11 90  0]
 [ 0 44 39 44 34 33  0]
 [ 0 54 95 76 86 82  0]
 [ 0  0  0  0  0  0  0]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [18]:
Z = np.diag(1+np.arange(4),k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [19]:
#w = np.ones((8,8))
w = np.zeros((8,8),dtype=int)
w[1::2,::2] = 1
w[::2,1::2] = 1
print(w)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [20]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [21]:
t = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(t)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [22]:
N=np.random.random((5,5))
N_min,N_max=N.min(),N.max()
N=(N-N_min)/(N_max-N_min)
print(N)

[[0.77970015 0.4281616  0.53080674 0.68205353 1.        ]
 [0.05854837 0.86453377 0.1398971  0.13037527 0.18464544]
 [0.96148341 0.93198844 0.41485499 0.91214293 0.        ]
 [0.28054097 0.93726988 0.07859456 0.07455286 0.47917238]
 [0.71130504 0.86431191 0.57703297 0.32558754 0.52287114]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [23]:
color = np.dtype([("r", np.ubyte, 1),("g", np.ubyte, 1),("b", np.ubyte, 1),("a", np.ubyte, 1)])
color

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [24]:
real= np.dot(np.ones((5,3)), np.ones((3,2)))
print(real)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [25]:
neg=np.arange(11)
neg[(neg>3) & (neg<=8)] *= -1
print(neg)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))


9


In [27]:
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [29]:
Z=np.arange(5)
print(Z**Z)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[  1   1   4  27 256]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [31]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [32]:
r = np.random.uniform(-5,+5,5)
print (np.copysign(np.ceil(np.abs(r)), r))

[ 3.  2. -5.  5. -2.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [33]:
h= np.random.randint(0,10,10)
i = np.random.randint(0,10,10)
print( np.intersect1d(h,i))

[0 1 2 5 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [34]:
# Suicide mode on  
defaults = np.seterr(all="ignore")  
Z = np.ones(1) / 0  
Z
# Back to sanity  
_ = np.seterr(**defaults)  
_

with np.errstate(divide='ignore'):  
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [35]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [36]:
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
today=np.datetime64('today','D')
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print(str(yesterday))
print(str(today))
print(str(tomorrow))

2022-04-10
2022-04-11
2022-04-12


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [37]:
july = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(july)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [38]:
A = np.ones(3)*1
B = np.ones(3)*2
print(np.add(A,B,out=B))


[3. 3. 3.]


In [39]:
print(np.divide(A,2,out=A))

[0.5 0.5 0.5]


In [40]:
print(np.negative(A,out=A))

[-0.5 -0.5 -0.5]


In [41]:
print(np.multiply(A,B,out=A))

[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [42]:
f = np.random.uniform(0,10,10)
print(f)
print (f - f%1)
print(np.floor(f))
print(np.ceil(f)-1)
print(f.astype(int))
print(np.trunc(f))

[8.42763337 0.1910108  3.65233024 8.3905744  3.32809779 2.32495593
 9.20707791 0.78763765 7.91094378 4.2549257 ]
[8. 0. 3. 8. 3. 2. 9. 0. 7. 4.]
[8. 0. 3. 8. 3. 2. 9. 0. 7. 4.]
[8. 0. 3. 8. 3. 2. 9. 0. 7. 4.]
[8 0 3 8 3 2 9 0 7 4]
[8. 0. 3. 8. 3. 2. 9. 0. 7. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [43]:
m1 = np.zeros((5,5))
m1+= np.arange(5)
print (m1)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [44]:
def generate():
     for j in range(10):
         yield j
J=np.fromiter(generate(),dtype=float,count=-1)
print(J)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [45]:
lin=np.linspace(0,1,11,endpoint=False)[1:]
lin

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [46]:
so=np.random.randint(100,size=10)
print(so)

[92 69 33 67 92 73 79 26  8 22]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [47]:
red= np.arange(10)
np.add.reduce(red)


45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [48]:
A = np.random.randint(1,10,5)
B = np.random.randint(1,10,5)
eql=np.allclose(A,B)
print(eql)
eql1=np.array_equal(A,B)
print(eql1)
print(A,B)

False
False
[8 2 2 3 4] [3 9 2 1 1]


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [49]:
imm=np.ones(10)
imm.flags.writeable=False
imm[2]=1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [50]:
Z = np.random.randint(100,size=(10,2))
X,Y = Z[:,0], Z[:,1]
print(X)
print(Y)
r = np.sqrt(X**2+Y**2)
tita = np.arctan2(Y,X)
print (r,tita)

[49 27 42 98 46 45 17 89 74 97]
[80 67  5 27 89 51 67 36 67 57]
[ 93.81364506  72.23572523  42.29657197 101.65136497 100.18482919
  68.01470429  69.12307864  96.00520819  99.82484661 112.50777751] [1.02123631 1.18771926 0.11848996 0.26884048 1.09375666 0.84781697
 1.32230891 0.38437483 0.7357935  0.53127341]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [51]:
q45 = np.random.randint(100,size=10)
q45[q45.argmax()]=0
q45

array([36, 59, 26, 72, 40,  0, 63,  0, 47, 71])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [52]:
q46 = np.zeros((5,5), [('x',float),('y',float)])
q46['x'], q46['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(q46)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [53]:
 X = np.arange(8)
 Y = X + 0.5
 C = 1.0 / np.subtract.outer(X, Y)
 print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [54]:
for dtype in [np.int8, np.int32, np.int64]:
     print(np.iinfo(dtype).min)
     print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
     print(np.finfo(dtype).min)
     print(np.finfo(dtype).max)
     print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [55]:
import sys
np.set_printoptions(threshold=sys.maxsize)
q49 = np.zeros((5,5))
print(q49)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [56]:
Z = np.arange(10)
print(Z)
v = np.random.uniform(0,10)
print(v)
index = (np.abs(Z-v)).argmin()
print (Z[index])

[0 1 2 3 4 5 6 7 8 9]
5.728948383193408
6


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [57]:
q51 = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),('color', [ ('r', float, 1),('g', float, 1),('b', float, 1)])])
print (q51)


[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [58]:
Z = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
print(D.shape)

[[0.         0.65150589 0.44761479 0.05862768 0.52426262 0.39819635
  0.15393468 0.40710123 0.13574376 0.26385549 0.14158692 0.50792723
  0.48783089 0.56194401 0.14674408 0.50848726 0.21490183 0.24696885
  0.00854355 0.04515748 0.57774196 0.59956516 0.33213871 0.07151266
  0.42283676 0.24229665 0.38615028 0.47881394 0.37887541 0.44770543
  0.34354257 0.20508359 0.52426602 0.40838379 0.46038725 0.06824634
  0.13879041 0.51955754 0.30156839 0.2821587  0.21121745 0.49650409
  0.46415381 0.27502367 0.47784391 0.519629   0.23531435 0.4774969
  0.61906036 0.59299048 0.58872062 0.49403005 0.71491163 0.40164882
  0.44885545 0.42531505 0.58624916 0.45413305 0.43342084 0.52070164
  0.28759617 0.32106851 0.47975097 0.297794   0.35460703 0.37928878
  0.3143122  0.3840321  0.41783403 0.51747998 0.43157909 0.40894623
  0.45125936 0.51838223 0.48435987 0.34410009 0.35726799 0.32293918
  0.72641094 0.49817447 0.61012002 0.40726868 0.72614882 0.44345495
  0.4154749  0.07850478 0.27133297 0.5631276  0.1

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [59]:
q53=np.arange(10, dtype=np.int32)
q53= q53.astype(np.float32, copy=False)
print (q53)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [60]:
q55 = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(q55):
  print (index, value)
for index in np.ndindex(q55.shape):
  print (index, q55[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [61]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [65]:
n = 10
p = 8
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),23)
print (Z)

[[ 0. 23. 23.  0.  0. 23.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 23.  0.  0.  0. 23.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 23.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 23.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 23.  0.  0.  0.  0.  0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [66]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.07228518 -0.37172675  0.51619404 -0.17144188  0.14021485 -0.26653236
   0.02112763  0.34846747 -0.2763996   0.13238177]
 [-0.01527598 -0.08241054 -0.29843887 -0.24718908  0.35510775  0.11911761
   0.2303761   0.42844968 -0.45802636 -0.03171031]
 [-0.08346611  0.10506109 -0.40831723  0.17553289 -0.14183446  0.08303981
   0.13788015  0.16660775  0.1260897  -0.16059359]
 [ 0.22649225  0.18743374 -0.59067912  0.16594415  0.14101342 -0.29194926
   0.17653458  0.2175828  -0.00150162 -0.23087093]
 [-0.37192091 -0.41440461 -0.01081879 -0.3604235   0.05370037  0.2893219
   0.58274149 -0.16219856  0.38326023  0.01074239]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [67]:
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[9 5 9]
 [4 1 9]
 [5 8 5]]
[[4 1 9]
 [9 5 9]
 [5 8 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [68]:
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [69]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.43057980519719075


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [70]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it:
  z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [72]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)


range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [73]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 1. 4. 1. 4. 4. 1. 2. 5. 6.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [74]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [130]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)

F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [129]:
A = np.random.randint(0,10,(3,4,3,4))

sum = A.sum(axis=(-2,-1))
print (sum)

[[60 42 60 36]
 [57 44 36 54]
 [62 43 47 59]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [128]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)

[0.47646336 0.52844384 0.54572513 0.35897675 0.35423829 0.26184206
 0.46522823 0.44509552 0.403948   0.35382962]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [127]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([2.79948687, 0.92543058, 1.24956286, 1.76260657, 0.36345099])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [126]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [125]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print (A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [124]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [123]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)


[( 7, 39) ( 7, 78) (16, 35) (16, 38) (18, 19) (18, 37) (19, 37) (20, 32)
 (20, 60) (22, 39) (22, 82) (24, 50) (24, 54) (32, 60) (32, 63) (32, 92)
 (35, 38) (39, 78) (39, 82) (42, 73) (42, 99) (50, 54) (52, 68) (52, 82)
 (63, 92) (68, 82) (72, 94) (72, 97) (73, 99) (94, 97)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [122]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [121]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [118]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)

print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [116]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [117]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.60426141,  0.27618228,  0.63771781,  0.46079527,  0.21994197,
        0.8203665 ,  0.30634082, -0.66477957, -0.19891328,  0.97638534,
        0.30224242, -0.16361529,  0.08770428, -0.34902342,  0.74169993,
       -0.67413077, -0.88393523,  0.0865722 ,  0.63500411, -0.91251104,
        0.34670414, -0.43962869, -0.16163017, -0.69367831, -0.68292817,
        0.12847086, -0.77764463, -0.75329309, -0.17637609, -0.10112394,
       -0.60244947, -0.48112665, -0.91920175, -0.2509523 ,  0.35108033,
        0.47308586,  0.25600963, -0.32960012, -0.77588131, -0.97618844,
       -0.29426263,  0.07905641,  0.66330287, -0.95412722, -0.27061793,
       -0.99511348,  0.47733351,  0.64151694,  0.12387569,  0.4522071 ,
        0.9612084 , -0.01743731,  0.70548113, -0.26095953,  0.52498202,
       -0.18172409, -0.21242912,  0.67225062,  0.29431991, -0.63087463,
       -0.98693934, -0.67567204, -0.3175081 ,  0.37817166, -0.18820015,
       -0.94662338,  0.0918864 ,  0.98136959, -0.55480848, -0.87

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [114]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))


[11.39241122  0.14760919  6.01155518 13.30260847  0.99507793  4.68528916
 14.61028669  0.66267504  7.69271349 13.48827677]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [115]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.98474994 12.2261797   4.47144749  3.25589435  6.72132234  1.84721846
  10.06979366  6.98255449  2.37656651  1.44345175]
 [ 5.32072072  3.50396561  2.83357517  4.08957711  2.27900524  6.43712171
   0.180504    2.27337172  6.81055705  6.96756922]
 [ 8.56581786  6.82678978  4.86964651  5.76179751  6.87544614  4.49030592
   8.92213474 12.33179215 16.91788828 17.37540365]
 [ 8.58042947 13.88982472  1.27666225  8.93368969 12.12801992  3.52119642
  13.54458585  9.2984051   4.59993931  2.77653829]
 [ 0.5878991   0.31432567  5.19998277  1.61679677  1.47889658  0.92658959
   0.83473893  5.17706697  9.84967924 11.21540251]
 [ 4.71342666  2.36140251  3.68173018  2.42730579  2.63528838  2.58808238
   4.01751269  7.64800139 12.26141585 13.04231533]
 [ 1.27080653  2.81969818  1.40532649  0.34649002  1.3395806   1.53148336
   1.2664441   2.35443459  6.97922556  7.94527147]
 [ 0.53988123  7.82589685  3.06340289  0.25956824  2.79281046  3.41752065
   5.34422946  2.40431677  2.18012375  2.84482234]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [113]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)

[[5 4 4 6 5 7 1 3 5 3]
 [3 1 3 9 1 6 2 1 2 7]
 [5 5 1 9 7 0 2 6 2 2]
 [6 8 1 2 2 4 2 2 4 2]
 [3 6 9 4 4 7 9 6 7 3]
 [3 2 0 9 2 4 3 6 3 3]
 [0 5 9 1 9 4 6 5 7 4]
 [5 1 1 5 6 3 0 5 8 6]
 [6 6 6 7 0 3 8 6 8 4]
 [7 6 9 5 8 0 1 8 9 7]]
[[0 0 0 0 0]
 [0 5 4 4 6]
 [0 3 1 3 9]
 [0 5 5 1 9]
 [0 6 8 1 2]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [119]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print (R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [111]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [110]:
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())


5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [120]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)


[[[[3 1 4]
   [4 4 3]
   [2 4 3]]

  [[1 4 3]
   [4 3 2]
   [4 3 1]]

  [[4 3 3]
   [3 2 0]
   [3 1 2]]

  [[3 3 4]
   [2 0 3]
   [1 2 3]]

  [[3 4 0]
   [0 3 1]
   [2 3 3]]

  [[4 0 0]
   [3 1 0]
   [3 3 2]]

  [[0 0 0]
   [1 0 1]
   [3 2 1]]

  [[0 0 1]
   [0 1 4]
   [2 1 2]]]


 [[[4 4 3]
   [2 4 3]
   [0 2 3]]

  [[4 3 2]
   [4 3 1]
   [2 3 3]]

  [[3 2 0]
   [3 1 2]
   [3 3 4]]

  [[2 0 3]
   [1 2 3]
   [3 4 2]]

  [[0 3 1]
   [2 3 3]
   [4 2 3]]

  [[3 1 0]
   [3 3 2]
   [2 3 2]]

  [[1 0 1]
   [3 2 1]
   [3 2 3]]

  [[0 1 4]
   [2 1 2]
   [2 3 3]]]


 [[[2 4 3]
   [0 2 3]
   [1 3 2]]

  [[4 3 1]
   [2 3 3]
   [3 2 4]]

  [[3 1 2]
   [3 3 4]
   [2 4 0]]

  [[1 2 3]
   [3 4 2]
   [4 0 1]]

  [[2 3 3]
   [4 2 3]
   [0 1 2]]

  [[3 3 2]
   [2 3 2]
   [1 2 1]]

  [[3 2 1]
   [3 2 3]
   [2 1 3]]

  [[2 1 2]
   [2 3 3]
   [1 3 2]]]


 [[[0 2 3]
   [1 3 2]
   [4 0 0]]

  [[2 3 3]
   [3 2 4]
   [0 0 4]]

  [[3 3 4]
   [2 4 0]
   [0 4 1]]

  [[3 4 2]
   [4 0 1]
   [4 1 0]]

  [[4 2 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [108]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 0 14 10  3  6]
 [14  5  0  6  4]
 [10  0  7 42 12]
 [ 3  6 42  8 13]
 [ 6  4 12 13  4]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [107]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [106]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [105]:
def iterate(Z):
  N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +Z[1:-1,0:-2]+ Z[1:-1,2:] + Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
  birth = (N==3) & (Z[1:-1,1:-1]==0)
  survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
  Z[...] = 0
  Z[1:-1,1:-1][birth | survive] = 1
  return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100):
  Z = iterate(Z)
  print (Z)


Streaming output truncated to the last 5000 lines.
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0
  0 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [103]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [104]:
print(Z[np.argpartition(-Z,n)[:n]])

[9999 9997 9998 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [101]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))


[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [100]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [92]:
x = np.random.rand()
np.power(x,3)

0.07507036276823446

In [99]:
np.einsum('i,i,i->i',x,x,x)

ValueError: ignored

In [94]:
x*x*x

0.07507036276823446

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [91]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[1 3 4 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [90]:
Z = np.random.randint(0,5,(10,3))
print (Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U)


[[0 3 0]
 [2 1 0]
 [3 4 4]
 [2 4 2]
 [4 0 3]
 [1 3 3]
 [3 1 3]
 [0 4 4]
 [2 0 1]
 [4 1 4]]
[[0 3 0]
 [2 1 0]
 [3 4 4]
 [2 4 2]
 [4 0 3]
 [1 3 3]
 [3 1 3]
 [0 4 4]
 [2 0 1]
 [4 1 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [88]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [89]:
print (np.unpackbits(I[:, np.newaxis], axis=1))

TypeError: ignored

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [85]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 0 0]
 [0 1 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [81]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))

sum
5.186210406045809


In [82]:
print ('A * B')
print (np.einsum('i,i->i', A, B)) 

A * B
[1.88186444e-01 6.30658113e-02 2.93684003e-02 3.19340230e-01
 1.33681441e-01 4.55471507e-01 3.84838842e-01 6.26689498e-04
 1.87674174e-02 7.90756331e-01]


In [83]:
print ('inner')
print (np.einsum('i,i', A, B))    # np.inner(A, B)

inner
2.384103113906164


In [84]:
print ('outer')
print (np.einsum('i,j->ij', A, B))    # np.outer(A, B)

outer
[[1.88186444e-01 7.67267584e-02 1.91619697e-02 2.33021669e-01
  5.60071700e-01 2.98432650e-01 5.59543955e-01 5.11430417e-02
  7.56371491e-02 5.19859638e-01]
 [1.54680466e-01 6.30658113e-02 1.57502440e-02 1.91532927e-01
  4.60352774e-01 2.45297698e-01 4.59918993e-01 4.20371912e-02
  6.21702033e-02 4.27300338e-01]
 [2.88422063e-01 1.17594495e-01 2.93684003e-02 3.57138321e-01
  8.58388264e-01 4.57389803e-01 8.57579422e-01 7.83838691e-02
  1.15924517e-01 7.96757651e-01]
 [2.57896626e-01 1.05148765e-01 2.62601664e-02 3.19340230e-01
  7.67539885e-01 4.08981497e-01 7.66816648e-01 7.00880341e-02
  1.03655530e-01 7.12432010e-01]
 [4.49175258e-02 1.83136260e-02 4.57369962e-03 5.56190798e-02
  1.33681441e-01 7.12317847e-02 1.33555476e-01 1.22071433e-02
  1.80535512e-02 1.24083373e-01]
 [2.87212419e-01 1.17101303e-01 2.92452291e-02 3.55640480e-01
  8.54788178e-01 4.55471507e-01 8.53982729e-01 7.80551266e-02
  1.15438329e-01 7.93416045e-01]
 [1.29429426e-01 5.27705403e-02 1.31790723e-02 1.602

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [78]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [77]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])


[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [75]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[-0.22034533  0.15794046]
